// GENERATED by gen-navy.cjs (POS-553 mockup): every declaration in the site's own
// styles that hard-codes one of the harbor's navies, re-emitted with the skin's
// base, panel or raised panel (each an "r, g, b" string). If the skin is
// picked, these navies become tokens instead.
export function navyOverrides({ base, panel, panel2 }) {
  return `
  html body .ai-veil { background:
      radial-gradient(80% 80% at 50% 50%, rgba(${panel}, 0.42), rgba(${base}, 0.78)),
      rgba(${panel}, 0.35) !important; background:
        radial-gradient(80% 80% at 50% 50%, rgba(${panel}, 0.42), rgba(${base}, 0.78)),
        rgba(${panel}, 0.35) !important; }
  html body .atlas-overlay { background: rgb(${base}) !important; background: rgb(${base}) !important; }
  html body .ao-bar { background: rgba(${panel}, 0.97) !important; }
  html body .cal-month-step { background: rgba(${panel}, 0.6) !important; }
  html body .cal-grid { background: rgba(${panel}, 0.6) !important; }
  html body .cal-day.is-out { background: rgba(${base}, 0.35) !important; }
  html body .cal-agenda-item { background: rgba(${panel}, 0.6) !important; }
  html body .hd { --hd-glass: rgba(${panel}, 0.62) !important; }
  html body .hd-public-note { background: rgba(${panel}, 0.8) !important; }
  html body .hd-cap { background: linear-gradient(transparent, rgba(${base}, 0.92) 40%) !important; }
  html body .keygen-key { background: rgb(${panel}) !important; }
  html body .c-tut { background: linear-gradient(var(--pm-harbor, rgb(${panel})), var(--pm-night, rgb(${base}))) !important; }
  html body .c-tut::backdrop { background: rgba(${base}, .72) !important; }
  html body .c-tut-call { background: rgba(${base}, .6) !important; }
  html body .mp-step, html body .mp-page { background: rgba(${panel}, 0.72) !important; }
  html body .mp-page.on { background: rgb(${panel2}) !important; }
  html body .pm-opsnav a[aria-current="page"] { color: rgb(${base}) !important; }
  html body .pm-res-card { background: rgba(${panel}, 0.72) !important; }
  html body .res-img-empty { background: rgba(${panel2}, 0.5) !important; }
  body { background:
      radial-gradient(120% 90% at 50% -10%, rgb(${panel2}) 0%, rgb(${panel}) 48%, rgb(${base}) 100%) fixed,
      rgb(${base}) !important; background: rgb(${base}) !important; }
  html body .prompt-box { background: rgb(${panel}) !important; }
  html body .pm-alert-pop { box-shadow: 0 14px 38px rgba(${base}, 0.5), 0 2px 8px rgba(${base}, 0.35) !important; }
  html body .pm-notif-panel { box-shadow: 0 14px 38px rgba(${base}, 0.5), 0 2px 8px rgba(${base}, 0.35) !important; }
  html body .pm-tut-card { box-shadow: 0 16px 44px rgba(${base}, 0.6), inset 0 0 24px rgba(0, 0, 0, 0.16) !important; }
  html body .jf-fields select { background: rgb(${panel}) !important; }
  html body .pm { --pm-night: rgb(${base}) !important; --pm-harbor: rgb(${panel}) !important; }
  html body .pm .pm-totop { background: rgba(${base}, 0.85) !important; }
  html body .pm .pm-btn.ghost { background: rgba(${panel}, 0.55) !important; }
  html body .pm-chip { background: rgba(${panel}, 0.6) !important; }
  html body .pm-chip.is-on, html body .pm-chip[aria-selected="true"], html body .pm-chip[aria-current="page"] { background: rgba(${panel2}, 0.65) !important; }
  html body .pm-chiprow--nav .pm-chip { background: rgba(${panel}, 0.6) !important; }
  html body .pm-chiprow--nav .pm-chip.is-on, html body .pm-chiprow--nav .pm-chip[aria-current="page"] { background: rgba(${panel2}, 0.6) !important; }
  html body .pm-chip.is-arriving { background: rgba(${panel}, 0.35) !important; }
  html body .profile-bubble { background: rgba(${base}, 0.78) !important; box-shadow: 0 18px 50px rgba(${base}, 0.18) !important; }
  html body .profile-edit-pencil { background: rgba(${base}, 0.72) !important; }
  html body .profile-edit-avatar-controls input[type="file"] { background: rgba(${panel}, 0.9) !important; }
  html body .profile-edit-grid input, html body .profile-edit-grid textarea { background: rgba(${panel}, 0.9) !important; }
  html body .bcard { background: rgba(${panel}, 0.72) !important; }
  html body .cards.has-open .bcard.active:hover::before { background: rgba(${base}, 0.72) !important; }
  html body .cards.has-open .bcard::after { background: rgba(${base}, 0.92) !important; }
  html body .bcard-emblem { background: rgba(${panel2}, 0.5) !important; }
  html body .rr-egg { background: rgba(${base}, 0.85) !important; }
  html body .corr-card { background: rgba(${panel}, 0.72) !important; }
  html body .corr-card.has-bg { background-image: linear-gradient(rgba(${base}, 0.86), rgba(${base}, 0.86)), var(--corr-bg) !important; }
  html body [data-quests] .quest-card { background: rgba(${panel}, 0.72) !important; }
  html body [data-stamps-bar] .seg-track { background: rgba(${panel2}, 0.55) !important; }
  html body [data-stamps-bar] .seg-holo { box-shadow: inset 1px 0 0 rgba(${panel}, 0.55) !important; }
  html body .board { background:
        radial-gradient(ellipse at 18% 6%, rgba(232, 196, 139, 0.16), transparent 55%),
        radial-gradient(ellipse at 88% 100%, rgba(${base}, 0.45), transparent 60%),
        repeating-radial-gradient(circle at 37% 61%, rgba(0, 0, 0, 0.1) 0 1px, transparent 1px 4px),
        repeating-radial-gradient(circle at 71% 23%, rgba(246, 220, 174, 0.05) 0 1px, transparent 1px 5px),
        linear-gradient(180deg, #655741, #443c30) !important; }
  html body .note-pop::backdrop { background: rgba(${base}, 0.62) !important; }
  html body .convo .c-say-gate, html body .convo .c-say-box { background: rgba(${panel}, 0.45) !important; }
  html body .convo .c-say-select { background: rgb(${panel}) !important; }
  html body .convo .c-say-text { background: rgb(${panel}) !important; }
  html body .convo .c-thread { background: rgba(${panel}, 0.6) !important; }
  html body .convo .c-more { background: rgba(${panel}, 0.4) !important; }
  html body .daily-shell iframe { background: rgb(${base}) !important; }
  html body .dx-card { background: rgba(${panel}, 0.72) !important; }
  html body .n-dial { background: rgba(${panel}, 0.72) !important; }
  html body .n-bar { background: rgba(${panel2}, 0.6) !important; }
  html body .repo-card { background: rgba(${panel}, 0.72) !important; }
  html body .cq { background:
      radial-gradient(120% 90% at 50% 0%, rgba(232, 196, 139, 0.07), transparent 60%),
      linear-gradient(var(--pm-harbor, rgb(${panel})), var(--pm-night, rgb(${base}))) !important; background:
        radial-gradient(120% 90% at 50% 0%, rgba(232, 196, 139, 0.07), transparent 60%),
        linear-gradient(var(--pm-harbor, rgb(${panel})), var(--pm-night, rgb(${base}))) !important; background:
      radial-gradient(120% 90% at 50% 0%, rgba(232, 196, 139, 0.07), transparent 60%),
      linear-gradient(var(--pm-harbor, rgb(${panel})), var(--pm-night, rgb(${base}))) !important; }
  html body .cq-ground { background: linear-gradient(rgba(70, 85, 119, 0.85), rgba(${panel2}, 0.95)) !important; background: linear-gradient(rgba(70, 85, 119, 0.85), rgba(${panel2}, 0.95)) !important; background: linear-gradient(rgba(70, 85, 119, 0.85), rgba(${panel2}, 0.95)) !important; }
  html body .cq-quay { background:
      linear-gradient(rgba(70, 85, 119, 0.55), rgba(${panel2}, 0.9)) !important; background: linear-gradient(rgba(70, 85, 119, 0.55), rgba(${panel2}, 0.9)) !important; background:
      linear-gradient(rgba(70, 85, 119, 0.55), rgba(${panel2}, 0.9)) !important; }
  html body .c-lane { background: rgba(${panel}, 0.4) !important; background: rgba(${panel}, 0.4) !important; }
  html body .s-tense, html body .s-card { background: rgba(${panel}, .72) !important; background: rgba(${panel}, .72) !important; }
  html body .s-example { background: rgba(${panel}, .6) !important; background: rgba(${panel}, .6) !important; }
  html body .s-viz { background: rgba(${base}, .5) !important; background: rgba(${base}, .5) !important; }
  html body .s-track { background: rgba(${panel2}, .55) !important; background: rgba(${panel2}, .55) !important; }
  html body .s-law blockquote { background: rgba(${base}, .45) !important; background: rgba(${base}, .45) !important; }
  html body .s-code { background: rgba(${base}, .6) !important; background: rgba(${base}, .6) !important; }
  html body .f-hero { background:
      radial-gradient(120% 80% at 0% 0%, rgba(232, 196, 139, .09), transparent 60%),
      rgba(${panel}, .72) !important; }
  html body .f-bar { background: rgba(${panel2}, .7) !important; }
  html body .f-draft { background: rgba(${panel}, .6) !important; }
  html body .f-law { background: rgba(${panel}, .55) !important; }
  html body .f-pay, html body .f-stake { background: rgba(${panel}, .5) !important; }
  html body .f-code { background: rgba(${panel2}, .5) !important; }
  html body .f-form input { background: rgba(${panel2}, .4) !important; }
  html body .f-how { background: rgba(${panel}, .5) !important; }
  html body .f-stake-form select, html body .f-stake-form input { background: rgba(${panel2}, .45) !important; }
  html body .f-fold { background: rgba(${panel}, .4) !important; }
  html body .dir-search input { background: rgba(${base}, 0.7) !important; }
  html body .hero-veil { background:
        linear-gradient(180deg, rgba(${base}, 0.66) 0%, rgba(${base}, 0) 30%, rgba(${base}, 0.82) 88%),
        radial-gradient(70% 46% at 50% 96%, rgba(${base}, 0.75), transparent 70%),
        radial-gradient(70% 34% at 50% 2%, rgba(${base}, 0.7), transparent 70%) !important; background: linear-gradient(180deg,
          rgba(${base}, 0.78) 0%,
          rgba(${base}, 0.30) 20%,
          rgba(${base}, 0.40) 42%,
          rgba(${base}, 0.82) 68%,
          rgba(${base}, 0.94) 100%) !important; }
  html body .ticker { background: rgba(${panel}, 0.72) !important; }
  html body .c-arrow { background: rgba(${panel}, 0.85) !important; }
  html body .c-arrow:hover { background: rgba(${panel2}, 0.95) !important; }
  html body .ao-close { background: rgba(${panel}, 0.9) !important; }
  html body .ao-close:hover { background: rgba(${panel2}, 0.95) !important; }
  html body .res-card { background: rgba(${panel}, 0.75) !important; }
  html body .works-grid .work { background: rgba(${panel}, 0.75) !important; }
  html body .fmt-example { background: rgb(${panel}) !important; }
  html body .paste textarea { background: rgb(${panel}) !important; }
  html body .rc-box { background: rgb(${panel}) !important; }
  html body .metrics { background: rgba(${panel}, 0.55) !important; }
  html body .filter-btn { background: rgba(${panel}, 0.72) !important; }
  html body .filter-panel { background: rgba(${panel}, 0.55) !important; }
  html body .fp-field input, html body .fp-field select { background: rgba(${base}, 0.7) !important; }
  html body .fr-composer textarea { background: rgb(${panel}) !important; }
  html body .meep-card { background: rgba(${base}, 0.78) !important; box-shadow: 0 18px 50px rgba(${base}, 0.18) !important; }
  html body .mc-face { background: var(--pm-night, rgb(${base})) !important; }
  html body .coop { background: linear-gradient(var(--pm-harbor, rgb(${panel})), var(--pm-night, rgb(${base}))) !important; }
  html body .bs-player-frame { background: rgb(${panel}) !important; }
  html body .bug-strip .bs-player-iframe { background: rgb(${panel}) !important; }
  html body .bc-root .bc-card { background: rgba(${panel}, 0.35) !important; }
  html body .bc-root .bc-name.bc-q { color: rgb(${panel}) !important; }
  html body .bc-root .bc-step::before { background: rgb(${panel}) !important; }
  html body .bc-root .bc-card .bc-step.is-reached.is-skipped::before { background: rgb(${panel}) !important; }
  html body [data-ops] .preview-line { background: rgb(${panel}) !important; }
  html body .opsgraph .og-asof { background: rgba(${panel}, 0.72) !important; }
  html body .opsgraph .og-chip { background: rgba(${panel}, 0.6) !important; }
  html body .opsgraph .og-chip.is-on { background: rgba(${panel2}, 0.75) !important; }
  html body .opsgraph .og-wear-badge::after { border: 0.5px solid rgb(${base}) !important; }
  html body .opsgraph .og-search { background: rgba(${panel}, 0.6) !important; }
  html body .opsgraph .og-zoom button { background: rgba(${base}, 0.86) !important; }
  html body .opsgraph .og-shelf-label { background: rgba(${base}, 0.86) !important; }
  html body .opsgraph .og-legend { background: rgba(${base}, 0.82) !important; }
  html body .opsgraph .og-claim { background: rgba(${base}, 0.94) !important; }
  html body .opsgraph .og-hint { background: rgba(${base}, 0.82) !important; }
  html body .opsgraph .og-panel { background: rgba(${panel}, 0.72) !important; }
  html body .opsgraph .og-finding { background: rgba(${base}, 0.45) !important; }
  html body .opsgraph .og-show { background: rgba(${panel2}, 0.8) !important; }
  html body .opsgraph .og-clause.is-walkable:hover { background: rgba(${panel2}, 0.8) !important; }
  html body .opsgraph .og-edgelist li:hover { background: rgba(${panel2}, 0.8) !important; }
  html body .opsgraph .og-why.is-walkable:hover { background: rgba(${panel2}, 0.8) !important; }
  html body .pj-card { background: rgba(${panel}, 0.72) !important; }
  html body .replay .r-feed { background: rgba(${panel}, 0.72) !important; }
  html body .replay .r-voice { background: rgba(${panel}, 0.6) !important; }
  html body .replay .r-settled { background: rgba(${panel}, 0.72) !important; }
  html body .replay .r-set-line { background: rgba(${panel}, 0.6) !important; }
  html body .replay .r-set:target .r-set-card { background: rgba(${panel}, 0.72) !important; }
  html body .rv-pick { background: rgba(${base}, 0.7) !important; }
  html body .s-split-holo { box-shadow: inset 1px 0 0 rgba(${panel}, .5) !important; }
  html body .votes .v-topic { background: rgba(${panel}, 0.55) !important; }
  html body .pm-tt-open { background: rgba(${panel}, 0.92) !important; }
  html body .pm-tt.is-armed .pm-tt-open { color: rgb(${panel}) !important; }
  html body .pm-tt-body { background: rgba(${panel}, 0.96) !important; }
  html body .pm-tt-back { color: rgb(${panel}) !important; }
`;
}
